backend:
  name: github
  repo: CreepilyCreeper/Relational-Structure-Visualizer
  branch: main
  auth_scope: repo
  client_id: Ov23li7JKJ2CH4t9foEA
  client_secret: ab41fc350001477d7732ab23eacb46728c8e2717

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "members"
    label: "Members"
    label_singular: "Member"
    description: "Manage community members"
    files:
      - file: "data/members.json"
        label: "Members List"
        name: "members"
        format: "json"
        fields:
          - { label: "Members", name: "members", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Testimonial", name: "testimonial", widget: "text" },
              { label: "Image", name: "image", widget: "image" }
            ] }